ui_ux_task:
  description: >
    Read the {resume} and create a user-friendly and visually appealing interface for a personal portfolio website.
    Make sure to use the information from the {resume} to create the website.Make the site more interactive and engaging.Extract
    each and every bit of information and write it on the website.
    Add some animations and transitions to the site.
  expected_output: >
    A detailed and functional website design page named ui_ux_design.md with all the necessary pages and sections.Detailed planning of every page and section.
  agent: ui_ux_designer


html_task:
  description: >
    Create a very well structured HTML file for a personal portfolio website.read the ui_ux_design file and create the html file accordingly.
    Make sure to use the semantic HTML tags and proper structure.Make it more interactive and engaging.Connect it to the styles.css file in the styles folder.
    Connect it to the script.js file in the scripts folder.put every information present in {resume} file in the index.html file.
    Add full details of every section Home, contact, full details of experience, projects, publications, awards, skills, education, etc.Write
    each and every information from the {resume} in the index.html file.
  expected_output: >
    An index.html file with necessary code and code only.
  agent: software_developer

css_task:
  description: >
    Design and implement a very attractive and responsive CSS for the portfolio website.Make it more interactive and engaging and colorful.
    Implement smooth transitions and hover effects for interactive elements.
    Use the ui_ux_design.md for the design and understanding the structure.
    This task depends on the ui_ux_task, html_task and javascript_task.
  expected_output: >
    A styles.css file with necessary code and code only.
  agent: software_developer

js_task:
  description: >
    Create a detailed and functional javascript file for the portfolio website.
    Make it more interactive and engaging.Add animations and transitions to the site.
    Use gsap library too for the animations and transitions.
    Use the ui_ux_design.md for the design and understanding the structure.
    This task depends on the ui_ux_task, html_task and css_task.
  expected_output: >
    A script.js file with necessary code and code only.
  agent: software_developer


